version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    container_name: gitlab
    user: root
    hostname: 'gitlab.ppj-international.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.ppj-international.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.ppj-international.com'
        
        # gitlab_rails['smtp_port'] = 587
        # gitlab_rails['smtp_user_name'] = 'nmtruong@ppj-international.com'
        # gitlab_rails['smtp_password'] = 'truongnm'
        # gitlab_rails['smtp_domain'] = 'mail.ppj-international.com'
        # gitlab_rails['smtp_authentication'] = 'login'
        # gitlab_rails['smtp_enable_starttls_auto'] = true
        # gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        # gitlab_rails['gitlab_email_from'] = 'nmtruong@ppj-international.com'
        # gitlab_rails['gitlab_email_reply_to'] = 'nmtruong@ppj-international.com'

        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'gitlabppj@ppj-international.com'
        gitlab_rails['smtp_password'] = 'GitlabPPJ*123@'
        gitlab_rails['smtp_domain'] = 'mail.ppj-international.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_display_name'] = 'gitlabppj'
        gitlab_rails['gitlab_email_from'] = 'gitlabppj@ppj-international.com'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlabppj@ppj-international.com'
        # gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        # gitlab_rails['gitlab_email_from'] = 'gitlabppj@ppj-international.com'
        # gitlab_rails['gitlab_email_reply_to'] = 'gitlabppj@ppj-international.com'
        # gitlab_rails['smtp_ssl'] = false
        # gitlab_rails['smtp_force_ssl'] = false
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '4443:443'
      - '2222:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '256m'